#!/bin/bash

echo "🎯 EMAIL TESTING GUIDE - WEB UI"
echo "================================"
echo ""
echo "📋 PRE-FLIGHT CHECK:"
echo ""

# Check if server is running
if ps aux | grep -v grep | grep "artisan serve" > /dev/null; then
    echo "✅ Server is running"
    ps aux | grep -v grep | grep "artisan serve" | awk '{print "   PID: " $2 " | Started: " $9}'
else
    echo "❌ Server is NOT running!"
    echo "   Run: php artisan serve --host=0.0.0.0"
    exit 1
fi

echo ""
echo "✅ OPcache cleared (server was just restarted)"
echo "✅ Logs cleared and ready"
echo ""

# Check email config
echo "📧 EMAIL CONFIGURATION:"
echo "   MAIL_MAILER: $(grep "^MAIL_MAILER=" .env | cut -d'=' -f2)"
echo "   MAIL_HOST: $(grep "^MAIL_HOST=" .env | cut -d'=' -f2)"
echo "   MAIL_FROM: $(grep "^MAIL_FROM_ADDRESS=" .env | cut -d'=' -f2)"
echo ""

echo "🧪 QUICK EMAIL TEST:"
php artisan email:test nkunzecaleb@gmail.com 2>&1 | grep -i "email sent\|error"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 NOW DO THIS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open a NEW terminal window and run:"
echo "   cd /Users/caleb/LGIHE/Dev/NEW/attendance/laravel-clockin"
echo "   tail -f storage/logs/laravel.log"
echo ""
echo "2. Go to your browser and create a user:"
echo "   - Navigate to: Users → Add New User"
echo "   - Fill in:"
echo "     • Name: Test User"
echo "     • Email: test@example.com"
echo "     • Password: Test123!"
echo "     • User Level: Any"
echo "   - Click 'Save'"
echo ""
echo "3. Watch the logs in the other terminal window"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 WHAT YOU SHOULD SEE IN LOGS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ EXPECTED (if working):"
echo "   [timestamp] UserForm: Creating new user via UI"
echo "   [timestamp] User created in database, preparing to send email"
echo "   [timestamp] Attempting to send account setup email"
echo "   [timestamp] Account setup email sent successfully"
echo ""
echo "❌ IF YOU SEE NOTHING:"
echo "   → Form validation failed OR"
echo "   → JavaScript error (check browser console) OR"
echo "   → Code still cached (unlikely after restart)"
echo ""
echo "⚠️  IF YOU SEE PARTIAL LOGS:"
echo "   → Check the error message in logs"
echo "   → SMTP issue or configuration problem"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After testing, check logs with:"
echo "  cat storage/logs/laravel.log"
echo ""
